spring.application.name=SysOdontologico

server.port=8081

spring.datasource.url=jdbc:h2:file:~/sysondotologico;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=1415


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.web=DEBUG


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

#spring.web.resources.cache.period=3600
#spring.web.resources.cache.cachecontrol.max-age=3600
#spring.web.resources.cache.cachecontrol.no-transform=true
#spring.web.resources.cache.cachecontrol.cache-public=true

server.compression.enabled=true
server.compression.min-response-size=1024
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,image/png,image/jpeg


